name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  build-windows:
    name: Build Linux Windows File
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21' # Replace with your Go version
      - name: Tidy Go modules
        run: go mod tidy
      - name: Build binary for Windows
        run: |
          $env:GOOS = "windows"
          $env:GOARCH = "amd64"
          go build -o confluence_cli-windows.exe
        shell: powershell
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: confluence_cli-windows
          path: confluence_cli-windows.exe

  build-linux:
    name: Build Linux Binary File
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21' # Replace with your Go version
      - name: Tidy Go modules
        run: go mod tidy
      - name: Build binary for Linux
        run: |
          GOOS=linux GOARCH=amd64 go build -o confluence_cli
      - name: Display structure
        run: ls -la
      - name: Upload artifact Linux
        uses: actions/upload-artifact@v4
        with:
          name: confluence_cli
          path: confluence_cli
      # - name: Create Release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     token: ${{ secrets.MY_GITHUB_TOKEN }}
      #     artifacts: "confluence_cli"
      #     tag: ${{ github.ref_name }}
      #     name: "Release ${{ github.ref_name }}"
      #     draft: false
      #     prerelease: false

  create-release:
    needs: [build-windows, build-linux]
    name: Release Project
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact Linux
        uses: actions/download-artifact@v4
        with:
          name: confluence_cli
      - name: Download artifact Windows
        uses: actions/download-artifact@v4
        with:
          name: confluence_cli-windows
      - name: Display structure of downloaded files
        run: ls -R
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          artifacts: "confluence_cli,confluence_cli-windows.exe"
          tag: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          draft: false
          prerelease: false
